export const HOSPITAL_ROLES = {
  BLOOD_BANK_COORDINATOR: 'BLOOD_BANK_COORDINATOR',
  HOSPITAL_ADMINISTRATOR: 'HOSPITAL_ADMINISTRATOR',
  MEDICAL_DIRECTOR: 'MEDICAL_DIRECTOR',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  SUPPLY_CHAIN_MANAGER: 'SUPPLY_CHAIN_MANAGER',
  IT_ADMIN: 'IT_ADMIN',
};

export const FEATURE_KEYS = {
  CRISIS_SCORE_GAUGE: 'CRISIS_SCORE_GAUGE',
  SIGNAL_BREAKDOWN: 'SIGNAL_BREAKDOWN',
  AI_CRISIS_BRIEF: 'AI_CRISIS_BRIEF',
  RANKED_ACTIONS: 'RANKED_ACTIONS',
  ANOMALY_SPARKLINES: 'ANOMALY_SPARKLINES',
  ADMISSION_PRESSURE: 'ADMISSION_PRESSURE',
  CASCADE_DIAGRAM: 'CASCADE_DIAGRAM',
  INVENTORY_STATUS: 'INVENTORY_STATUS',
  TIME_TO_EXHAUSTION: 'TIME_TO_EXHAUSTION',
  FINANCIAL_IMPACT: 'FINANCIAL_IMPACT',
  EVENT_HISTORY: 'EVENT_HISTORY',
  ACKNOWLEDGE_ALERT: 'ACKNOWLEDGE_ALERT',
  LOG_ACTION: 'LOG_ACTION',
  EMERGENCY_PROTOCOL: 'EMERGENCY_PROTOCOL',
  EXPORT_REPORT: 'EXPORT_REPORT',
  SYSTEM_HEALTH: 'SYSTEM_HEALTH',
};

const ALL_FEATURES = Object.values(FEATURE_KEYS);

const roleFeatures = {
  [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR]: {
    accessLevel: 'FULL',
    refreshRateMs: 60000,
    alertThreshold: 60,
    canSee: ALL_FEATURES.filter((f) => f !== FEATURE_KEYS.FINANCIAL_IMPACT && f !== FEATURE_KEYS.SYSTEM_HEALTH),
    canDo: [
      FEATURE_KEYS.ACKNOWLEDGE_ALERT,
      FEATURE_KEYS.LOG_ACTION,
      FEATURE_KEYS.RANKED_ACTIONS,
      FEATURE_KEYS.INVENTORY_STATUS,
      FEATURE_KEYS.TIME_TO_EXHAUSTION,
    ],
  },
  [HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR]: {
    accessLevel: 'STRATEGIC',
    refreshRateMs: 300000,
    alertThreshold: 80,
    canSee: [
      FEATURE_KEYS.CRISIS_SCORE_GAUGE,
      FEATURE_KEYS.AI_CRISIS_BRIEF,
      FEATURE_KEYS.RANKED_ACTIONS,
      FEATURE_KEYS.FINANCIAL_IMPACT,
      FEATURE_KEYS.EVENT_HISTORY,
      FEATURE_KEYS.EXPORT_REPORT,
      FEATURE_KEYS.INVENTORY_STATUS,
      FEATURE_KEYS.TIME_TO_EXHAUSTION,
    ],
    canDo: [FEATURE_KEYS.EXPORT_REPORT],
  },
  [HOSPITAL_ROLES.MEDICAL_DIRECTOR]: {
    accessLevel: 'CLINICAL',
    refreshRateMs: 60000,
    alertThreshold: 0,
    canSee: ALL_FEATURES.filter((f) => f !== FEATURE_KEYS.SYSTEM_HEALTH),
    canDo: [
      FEATURE_KEYS.ACKNOWLEDGE_ALERT,
      FEATURE_KEYS.LOG_ACTION,
      FEATURE_KEYS.EMERGENCY_PROTOCOL,
      FEATURE_KEYS.RANKED_ACTIONS,
      FEATURE_KEYS.EXPORT_REPORT,
      FEATURE_KEYS.INVENTORY_STATUS,
      FEATURE_KEYS.TIME_TO_EXHAUSTION,
    ],
  },
  [HOSPITAL_ROLES.DEPARTMENT_HEAD]: {
    accessLevel: 'WARD_LIMITED',
    refreshRateMs: 600000,
    alertThreshold: 60,
    canSee: [FEATURE_KEYS.INVENTORY_STATUS, FEATURE_KEYS.TIME_TO_EXHAUSTION, FEATURE_KEYS.ADMISSION_PRESSURE, FEATURE_KEYS.RANKED_ACTIONS],
    canDo: [FEATURE_KEYS.LOG_ACTION],
  },
  [HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER]: {
    accessLevel: 'SUPPLY_FOCUSED',
    refreshRateMs: 300000,
    alertThreshold: 20,
    canSee: [
      FEATURE_KEYS.CRISIS_SCORE_GAUGE,
      FEATURE_KEYS.RANKED_ACTIONS,
      FEATURE_KEYS.TIME_TO_EXHAUSTION,
      FEATURE_KEYS.EVENT_HISTORY,
      FEATURE_KEYS.FINANCIAL_IMPACT,
      FEATURE_KEYS.INVENTORY_STATUS,
      FEATURE_KEYS.AI_CRISIS_BRIEF,
    ],
    canDo: [FEATURE_KEYS.RANKED_ACTIONS, FEATURE_KEYS.LOG_ACTION],
  },
  [HOSPITAL_ROLES.IT_ADMIN]: {
    accessLevel: 'SYSTEM',
    refreshRateMs: 60000,
    alertThreshold: 101,
    canSee: ALL_FEATURES,
    canDo: ALL_FEATURES,
  },
};

const featureVisibility = {
  [FEATURE_KEYS.CRISIS_SCORE_GAUGE]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.SIGNAL_BREAKDOWN]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.AI_CRISIS_BRIEF]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.RANKED_ACTIONS]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.DEPARTMENT_HEAD, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.ANOMALY_SPARKLINES]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.ADMISSION_PRESSURE]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.DEPARTMENT_HEAD, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.CASCADE_DIAGRAM]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.INVENTORY_STATUS]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.DEPARTMENT_HEAD, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.TIME_TO_EXHAUSTION]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.DEPARTMENT_HEAD, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.FINANCIAL_IMPACT]: [HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.EVENT_HISTORY]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.ACKNOWLEDGE_ALERT]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR],
  [FEATURE_KEYS.LOG_ACTION]: [HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR],
  [FEATURE_KEYS.EMERGENCY_PROTOCOL]: [HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.EXPORT_REPORT]: [HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.MEDICAL_DIRECTOR, HOSPITAL_ROLES.IT_ADMIN],
  [FEATURE_KEYS.SYSTEM_HEALTH]: [HOSPITAL_ROLES.IT_ADMIN],
};

const readOnlyRolesByFeature = {
  [FEATURE_KEYS.RANKED_ACTIONS]: [HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR, HOSPITAL_ROLES.DEPARTMENT_HEAD],
  [FEATURE_KEYS.AI_CRISIS_BRIEF]: [HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR],
};

export function mapTokenRoleToHospitalRole(tokenRole) {
  if (!tokenRole) return HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR;
  const normalized = String(tokenRole).toLowerCase();
  if (normalized === 'hospital_admin') return HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR;
  if (normalized === 'blood_bank_coordinator') return HOSPITAL_ROLES.BLOOD_BANK_COORDINATOR;
  if (normalized === 'medical_director') return HOSPITAL_ROLES.MEDICAL_DIRECTOR;
  if (normalized === 'department_head') return HOSPITAL_ROLES.DEPARTMENT_HEAD;
  if (normalized === 'supply_chain_manager') return HOSPITAL_ROLES.SUPPLY_CHAIN_MANAGER;
  if (normalized === 'it_admin') return HOSPITAL_ROLES.IT_ADMIN;
  return HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR;
}

export function getRoleConfig(role) {
  return roleFeatures[role] || roleFeatures[HOSPITAL_ROLES.HOSPITAL_ADMINISTRATOR];
}

export function canRoleSeeFeature(role, featureKey) {
  return (featureVisibility[featureKey] || []).includes(role);
}

export function isFeatureReadOnly(role, featureKey) {
  return (readOnlyRolesByFeature[featureKey] || []).includes(role);
}
